spring:
  application:
    name: service-turbine
server:
  port: 8769

turbine:
  agaregator:
    clusterConfig: default
  app-config: ribbon-restTemplate,ribbon-feign
  cluster-name-expression: new String("default")
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
