#数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chapter?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456



