spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  application:
    name: config-server
server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/